# 读取并查看 P2P 网络贷款数据主表的基本信息

In [7]:
import pandas as pd

master_data = pd.read_csv("../data/Training_Master.csv",sep = ",",encoding = "gbk")

# 使用ndim、shape、memory_usage属性分别查看维度、大小、占用内存信息

print("P2P网络贷款数据主表的维度为：",master_data.ndim)
print("P2P网络贷款数据主表的元素形状（大小）为：",master_data.shape)
print("P2P网络贷款数据主表的占用内存信息为：\n",master_data.memory_usage)

P2P网络贷款数据主表的维度为： 2
P2P网络贷款数据主表的元素形状（大小）为： (30000, 228)
P2P网络贷款数据主表的占用内存信息为：
 <bound method DataFrame.memory_usage of          Idx  UserInfo_1  UserInfo_2  UserInfo_3  UserInfo_4  WeblogInfo_1  \
0      10001         1.0          深圳         4.0          深圳           NaN
1      10002         1.0          温州         4.0          温州           NaN
2      10003         1.0          宜昌         3.0          宜昌           NaN
3      10006         4.0          南平         1.0          南平           NaN
4      10007         5.0          辽阳         1.0          辽阳           NaN
5      10008         1.0          吴忠         5.0          银川           NaN
6      10011         1.0          绵阳         3.0          赤峰           NaN
7      10015         4.0          东莞         5.0          东莞           NaN
8      10019         1.0          赤峰         6.0          赤峰           NaN
9      10021         3.0          武汉         5.0          鄂州           NaN
10     10022         5.0          武汉         5.0          武汉           NaN
11     10024         5.0          长沙         5.0          长沙           NaN
12     10026         3.0          漳州         3.0          漳州           NaN
13     10027         3.0         牡丹江         6.0         牡丹江           NaN
14     10031         1.0          太原         3.0          太原           NaN
15     10032         1.0          北京         6.0          北京           NaN
16     10036         1.0          成都         3.0          忻州           NaN
17     10039         1.0          三明         4.0          三明           NaN
18     10040         1.0          临沂         6.0          临沂           NaN
19     10044         4.0          临沂         6.0          临沂           NaN
20     10050         1.0          福州         5.0          福州           NaN
21     10054         4.0          泰州         4.0          泰州           NaN
22     10059         5.0          成都         4.0          大同           NaN
23      1006         4.0          上海         5.0          上海           NaN
24     10063         1.0  红河哈尼族彝族自治州         5.0  红河哈尼族彝族自治州           NaN
25     10067         4.0          南平         4.0          南平           NaN
26     10068         1.0          郴州         5.0          郴州           NaN
27     10069         3.0          常州         4.0          常州           NaN
28      1007         6.0          湖州         6.0          湖州           NaN
29     10070         4.0          茂名         1.0          佛山           NaN
...      ...         ...         ...         ...         ...           ...
29970   9905         1.0          咸宁         4.0          温州           NaN
29971    991         1.0          惠州         4.0          揭阳           NaN
29972   9912         1.0          温州         5.0          温州           NaN
29973   9914         3.0          常德         5.0          常德           NaN
29974   9918         3.0          赣州         1.0          东莞           NaN
29975   9919         5.0          镇江         3.0          镇江           NaN
29976    992         5.0          淮安         3.0          上海           NaN
29977   9921         6.0          福州         6.0          福州           NaN
29978   9923         5.0          三明         6.0          三明           NaN
29979   9926         1.0          深圳         5.0          东莞           NaN
29980   9935         1.0         NaN         4.0         NaN           NaN
29981   9936         5.0          惠州         1.0          深圳           NaN
29982   9938         1.0          泉州         6.0          泉州           NaN
29983   9941         1.0          衡阳         6.0          广州           NaN
29984   9952         1.0     临夏回族自治州         3.0     临夏回族自治州           NaN
29985   9964         1.0          南昌         4.0          深圳           NaN
29986   9966         1.0          佛山         3.0         NaN           NaN
29987   9967         7.0          扬州         5.0          扬州           NaN
29988   9974         1.0          荆门         6.0          荆门           NaN
29989   9979         4.0          青岛         5.0          青岛           NaN
29990   9983         6.0          上海         5.0          上海           NaN
29991   9984         4.0          晋中         4.0          晋中           NaN
29992   9986         1.0          运城         5.0          运城           NaN
29993   9989         1.0          北京         3.0          北京           NaN
29994   9990         4.0          酒泉         6.0         嘉峪关           NaN
29995   9991         3.0          南阳         4.0          南阳           NaN
29996   9992         3.0          宁德         4.0          泉州           NaN
29997   9995         1.0          天津         2.0          天津           NaN
29998   9997         3.0          运城         3.0          运城           NaN
29999   9998         4.0          金华         5.0          无锡           NaN

       WeblogInfo_2  WeblogInfo_3  WeblogInfo_4  WeblogInfo_5     ...       \
0               1.0           NaN           1.0           1.0     ...
1               0.0           NaN           1.0           1.0     ...
2               0.0           NaN           2.0           2.0     ...
3               NaN           NaN           NaN           NaN     ...
4               0.0           NaN           1.0           1.0     ...
5               0.0           NaN           2.0           2.0     ...
6               0.0           NaN          13.0           1.0     ...
7               0.0           NaN          12.0           6.0     ...
8               0.0           NaN          10.0           6.0     ...
9               0.0           NaN           1.0           1.0     ...
10              0.0           NaN           3.0           2.0     ...
11              1.0           NaN           1.0           1.0     ...
12              1.0           NaN          11.0           3.0     ...
13              0.0           NaN           1.0           1.0     ...
14              0.0           NaN           3.0           1.0     ...
15              0.0           NaN           2.0           2.0     ...
16              0.0           NaN           4.0           3.0     ...
17              0.0           NaN           4.0           2.0     ...
18              0.0           NaN           1.0           1.0     ...
19              0.0           NaN           2.0           2.0     ...
20              0.0           NaN           3.0           2.0     ...
21              0.0           NaN           3.0           2.0     ...
22              0.0           NaN           8.0           8.0     ...
23              1.0           NaN           1.0           1.0     ...
24              0.0           NaN           1.0           1.0     ...
25              0.0           NaN           2.0           1.0     ...
26              0.0           NaN           9.0           5.0     ...
27              0.0           NaN           2.0           2.0     ...
28              0.0           NaN           2.0           2.0     ...
29              0.0           NaN           2.0           1.0     ...
...             ...           ...           ...           ...     ...
29970           0.0           NaN           2.0           1.0     ...
29971           1.0           NaN           8.0           3.0     ...
29972           0.0           NaN           5.0           5.0     ...
29973           0.0           NaN           6.0           1.0     ...
29974           0.0           NaN          13.0          11.0     ...
29975           0.0           NaN           8.0           1.0     ...
29976           0.0           NaN           3.0           2.0     ...
29977           0.0           NaN           1.0           1.0     ...
29978           1.0           NaN           6.0           3.0     ...
29979           0.0           NaN           4.0           3.0     ...
29980           0.0           NaN           1.0           1.0     ...
29981           0.0           NaN           4.0           4.0     ...
29982           0.0           NaN           3.0           1.0     ...
29983           0.0           NaN           2.0           2.0     ...
29984           0.0           NaN           2.0           1.0     ...
29985           1.0           NaN           2.0           2.0     ...
29986           0.0           NaN           3.0           1.0     ...
29987           0.0           NaN           5.0           3.0     ...
29988           0.0           NaN           1.0           1.0     ...
29989           0.0           NaN          12.0           3.0     ...
29990           1.0           NaN           2.0           2.0     ...
29991           0.0           NaN           7.0           2.0     ...
29992           0.0           NaN           3.0           3.0     ...
29993           0.0           NaN           5.0           4.0     ...
29994           NaN           NaN           NaN           NaN     ...
29995           1.0           NaN           3.0           2.0     ...
29996           0.0           NaN           6.0           1.0     ...
29997           0.0           NaN           2.0           2.0     ...
29998           0.0           NaN           1.0           1.0     ...
29999           0.0           NaN           1.0           1.0     ...

       SocialNetwork_10  SocialNetwork_11  SocialNetwork_12  SocialNetwork_13  \
0                   222                -1                 0                 0
1                     1                -1                 0                 0
2                    -1                -1                -1                 1
3                    -1                -1                -1                 0
4                    -1                -1                -1                 0
5                    -1                -1                -1                 0
6                    14                -1                 0                 1
7                   559                -1                 0                 1
8                    -1                -1                -1                 0
9                    -1                -1                -1                 1
10                   -1                -1                -1                 0
11                   -1                -1                -1                 0
12                  111                -1                 0                 1
13                   -1                -1                -1                 0
14                  572                -1                 0                 1
15                   88                -1                 0                 1
16                   -1                -1                -1                 0
17                  105                -1                 0                 0
18                   -1                -1                -1                 0
19                   -1                -1                -1                 0
20                  250                -1                 0                 1
21                   18                -1                 0                 0
22                   52                -1                 0                 1
23                  452                -1                 0                 0
24                   -1                -1                -1                 1
25                   37                -1                 0                 1
26                   85                -1                 0                 0
27                  112                -1                 0                 0
28                   -1                -1                -1                 0
29                   -1                -1                -1                 0
...                 ...               ...               ...               ...
29970                -1                -1                -1                 0
29971                -1                -1                -1                 0
29972               318                -1                 0                 0
29973                -1                -1                -1                 0
29974               194                -1                 0                 1
29975                38                -1                 0                 0
29976                -1                -1                -1                 1
29977                -1                -1                -1                 0
29978                -1                -1                -1                 0
29979                -1                -1                -1                 0
29980                -1                -1                -1                 0
29981                -1                -1                -1                 0
29982                 5                -1                 0                 1
29983                -1                -1                -1                 0
29984                -1                -1                -1                 1
29985                 1                -1                 0                 1
29986                -1                -1                -1                 0
29987                -1                -1                -1                 1
29988                -1                -1                -1                 0
29989                15                -1                 0                 1
29990               640                -1                 0                 1
29991               230                -1                 0                 0
29992                -1                -1                -1                 0
29993                -1                -1                -1                 1
29994                -1                -1                -1                 0
29995                 0                -1                 0                 1
29996               407                -1                 0                 0
29997                -1                -1                -1                 0
29998               612                -1                 0                 1
29999                -1                -1                -1                 0

       SocialNetwork_14  SocialNetwork_15  SocialNetwork_16  SocialNetwork_17  \
0                     0                 0                 0                 1
1                     0                 0                 0                 2
2                     0                 0                 0                 0
3                     0                 0                 0                 0
4                     0                 0                 0                 0
5                     0                 0                 0                 0
6                     0                 0                 0                 1
7                     0                 0                 0                 1
8                     0                 0                 1                 0
9                     0                 0                 0                 0
10                    0                 0                 0                 0
11                    0                 0                 0                 0
12                    0                 0                 0                 1
13                    0                 0                 0                 0
14                    0                 0                 0                 1
15                    1                 0                 0                 1
16                    0                 0                 0                 0
17                    0                 0                 0                 1
18                    0                 0                 0                 0
19                    0                 0                 0                 0
20                    1                 0                 0                 1
21                    0                 0                 0                 1
22                    0                 0                 0                 1
23                    0                 0                 0                 1
24                    1                 0                 0                 0
25                    0                 0                 0                 1
26                    1                 0                 0                 1
27                    0                 0                 0                 1
28                    0                 1                 0                 0
29                    0                 0                 0                 0
...                 ...               ...               ...               ...
29970                 0                 0                 0                 0
29971                 0                 0                 0                 0
29972                 0                 0                 0                 1
29973                 0                 0                 0                 0
29974                 1                 0                 0                 1
29975                 0                 0                 0                 1
29976                 0                 0                 0                 0
29977                 0                 0                 0                 0
29978                 0                 0                 0                 0
29979                 0                 0                 0                 0
29980                 0                 0                 0                 0
29981                 0                 0                 0                 0
29982                 1                 0                 0                 1
29983                 0                 0                 0                 0
29984                 0                 0                 0                 0
29985                 0                 0                 0                 1
29986                 0                 0                 0                 0
29987                 0                 0                 0                 0
29988                 0                 0                 0                 0
29989                 0                 1                 0                 1
29990                 0                 0                 0                 1
29991                 0                 0                 0                 1
29992                 0                 0                 0                 0
29993                 0                 0                 0                 0
29994                 0                 0                 0                 0
29995                 0                 0                 0                 1
29996                 0                 0                 0                 1
29997                 0                 0                 0                 0
29998                 0                 0                 0                 1
29999                 0                 0                 0                 0

       target  ListingInfo
0           0     2014/3/5
1           0    2014/2/26
2           0    2014/2/28
3           0    2014/2/25
4           0    2014/2/27
5           0    2014/2/27
6           1    2014/2/24
7           0    2014/2/28
8           1    2014/2/24
9           0    2014/2/27
10          0    2014/2/25
11          0     2014/3/6
12          0     2014/3/4
13          1    2014/2/26
14          0     2014/3/7
15          0    2014/2/26
16          0    2014/2/27
17          0    2014/2/22
18          1    2014/2/23
19          0    2014/2/24
20          0    2014/2/26
21          0    2014/2/24
22          0    2014/2/26
23          0   2013/11/18
24          0    2014/2/22
25          0    2014/2/25
26          0     2014/3/4
27          0    2014/2/24
28          0   2013/11/18
29          0     2014/3/3
...       ...          ...
29970       0     2014/3/4
29971       0   2013/11/21
29972       0     2014/3/5
29973       0     2014/3/7
29974       0    2014/2/20
29975       0    2014/2/28
29976       0   2013/11/15
29977       0    2014/2/26
29978       0    2014/3/10
29979       0    2014/2/21
29980       0    2014/2/24
29981       0    2014/2/27

In [8]:
# 使用describe方法进行描述性统计

print("P2P网络贷款数据主表的描述性统计结果为：",master_data.describe())

P2P网络贷款数据主表的描述性统计结果为：                 Idx    UserInfo_1    UserInfo_3  WeblogInfo_1  WeblogInfo_2  \
count  30000.000000  29994.000000  29993.000000    970.000000  28342.000000
mean   46318.673267      3.219911      4.694329      2.201031      0.131466
std    26640.397805      1.827684      1.321458      7.831679      0.358486
min        3.000000      0.000000      0.000000      1.000000      0.000000
25%    22924.250000      1.000000      4.000000      1.000000      0.000000
50%    46849.500000      3.000000      5.000000      1.000000      0.000000
75%    69447.250000      5.000000      5.000000      1.000000      0.000000
max    91703.000000      7.000000      7.000000    133.000000      4.000000

       WeblogInfo_3  WeblogInfo_4  WeblogInfo_5  WeblogInfo_6  WeblogInfo_7  \
count    970.000000  28349.000000  28349.000000  28349.000000  30000.000000
mean       1.308247      3.025962      1.816960      2.948711     10.632800
std        7.866457      3.772421      1.701177      3.770300     16.097588
min        0.000000      1.000000      1.000000      1.000000      0.000000
25%        0.000000      1.000000      1.000000      1.000000      2.000000
50%        0.000000      2.000000      1.000000      2.000000      6.000000
75%        1.000000      3.000000      2.000000      3.000000     13.000000
max      133.000000    165.000000     73.000000    165.000000    722.000000

           ...       SocialNetwork_9  SocialNetwork_10  SocialNetwork_11  \
count      ...          30000.000000      30000.000000      30000.000000
mean       ...             35.516167         75.211233         -0.999267
std        ...            135.954587        742.978305          0.052911
min        ...             -1.000000         -1.000000         -1.000000
25%        ...             -1.000000         -1.000000         -1.000000
50%        ...             -1.000000         -1.000000         -1.000000
75%        ...             -1.000000         -1.000000         -1.000000
max        ...           3242.000000      71253.000000          6.000000

       SocialNetwork_12  SocialNetwork_13  SocialNetwork_14  SocialNetwork_15  \
count      30000.000000      30000.000000      30000.000000      30000.000000
mean          -0.745033          0.221167          0.062033          0.027967
std            0.441473          0.420545          0.242598          0.164880
min           -1.000000          0.000000          0.000000          0.000000
25%           -1.000000          0.000000          0.000000          0.000000
50%           -1.000000          0.000000          0.000000          0.000000
75%            0.000000          0.000000          0.000000          0.000000
max            1.000000          2.000000          3.000000          1.000000

       SocialNetwork_16  SocialNetwork_17        target
count      30000.000000      30000.000000  30000.000000
mean           0.016633          0.253467      0.073267
std            0.127895          0.437296      0.260578
min            0.000000          0.000000      0.000000
25%            0.000000          0.000000      0.000000
50%            0.000000          0.000000      0.000000
75%            0.000000          1.000000      0.000000
max            1.000000          3.000000      1.000000

[8 rows x 208 columns]

In [9]:
# 剔除值相同或全为空的列

# 定义一个函数剔除全为空值的列和标准差为0的列

def dropNullStd(data):
    beforelen = data.shape[1]
    colisNull = data.describe().loc["count"] == 0
    for i in range(len(colisNull)):
        if colisNull[i]:
            data.drop(colisNull.index[i],axis = 1,inplace = True)
    
    stdisZero = data.describe().loc["std"] == 0
    for i in range(len(stdisZero)):
        if stdisZero[i]:
            data.drop(stdisZero.index[i],axis = 1,inplace = True)
    afterlen = data.shape[1]
    print("剔除的列的数目为：",beforelen-afterlen)
    print("剔除后数据的形状为：",data.shape)

dropNullStd(master_data)

剔除的列的数目为： 2
剔除后数据的形状为： (30000, 226)

# 读取 mtcars 数据集

In [1]:
import pandas as pd

mtcars_data = pd.read_csv("../data/mtcars.csv",sep = ",",encoding = "gbk")

# 查看mtcars数据集的维度、大小等信息

print("mtcars数据集的维度为：",mtcars_data.ndim)
print("mtcars数据集的元素形状（大小）为：",mtcars_data.shape)
print("mtcars数据集的元素个数为：",mtcars_data.size)
print("mtcars数据集的占用内存信息为：\n",mtcars_data.memory_usage)

mtcars数据集的维度为： 2
mtcars数据集的元素形状（大小）为： (32, 12)
mtcars数据集的元素个数为： 384
mtcars数据集的占用内存信息为：
 <bound method DataFrame.memory_usage of              Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3
13     3     3
14     3     4
15     3     4
16     3     4
17     4     1
18     4     2
19     4     1
20     3     1
21     3     2
22     3     2
23     3     4
24     3     2
25     4     1
26     5     2
27     5     2
28     5     4
29     5     6
30     5     8
31     4     2  >

In [7]:
# 使用describe方法对整个mtcars数据集进行描述性统计

print("mtcars数据集的描述性统计结果为：\n",mtcars_data.describe())

mtcars数据集的描述性统计结果为：
              mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000

            qsec         vs         am       gear     carb
count  32.000000  32.000000  32.000000  32.000000  32.0000
mean   17.848750   0.437500   0.406250   3.687500   2.8125
std     1.786943   0.504016   0.498991   0.737804   1.6152
min    14.500000   0.000000   0.000000   3.000000   1.0000
25%    16.892500   0.000000   0.000000   3.000000   2.0000
50%    17.710000   0.000000   0.000000   4.000000   2.0000
75%    18.900000   1.000000   1.000000   4.000000   4.0000
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [6]:
# 计算不同cyl(汽缸数)、carb(化油器)对应的mpg(油耗)和hp(马力)的均值

mtcars_data_group = mtcars_data[["cyl","carb","mpg","hp"]].groupby(by = ["cyl","carb"])
print("不同cyl(汽缸数)、carb(化油器)对应的mpg(油耗)和hp(马力)的均值结果为：\n",mtcars_data_group.mean())

不同cyl(汽缸数)、carb(化油器)对应的mpg(油耗)和hp(马力)的均值结果为：
             mpg     hp
cyl carb
4   1     27.58   77.4
    2     25.90   87.0
6   1     19.75  107.5
    4     19.75  116.5
    6     19.70  175.0
8   2     17.15  162.5
    3     16.30  180.0
    4     13.15  234.0
    8     15.00  335.0